// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: message/message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageService_MessageUnary_FullMethodName              = "/message.MessageService/MessageUnary"
	MessageService_MessageServerStream_FullMethodName       = "/message.MessageService/MessageServerStream"
	MessageService_MessageServerStreamFactor_FullMethodName = "/message.MessageService/MessageServerStreamFactor"
)

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	MessageUnary(ctx context.Context, in *MessageUnaryReq, opts ...grpc.CallOption) (*MessageUnaryRes, error)
	MessageServerStream(ctx context.Context, in *MessaageServerStreamReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageServerStreamRes], error)
	MessageServerStreamFactor(ctx context.Context, in *MessageServiceStreamFactorReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageServiceStreamFactorRes], error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) MessageUnary(ctx context.Context, in *MessageUnaryReq, opts ...grpc.CallOption) (*MessageUnaryRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageUnaryRes)
	err := c.cc.Invoke(ctx, MessageService_MessageUnary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) MessageServerStream(ctx context.Context, in *MessaageServerStreamReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageServerStreamRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageService_ServiceDesc.Streams[0], MessageService_MessageServerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MessaageServerStreamReq, MessageServerStreamRes]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageService_MessageServerStreamClient = grpc.ServerStreamingClient[MessageServerStreamRes]

func (c *messageServiceClient) MessageServerStreamFactor(ctx context.Context, in *MessageServiceStreamFactorReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageServiceStreamFactorRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageService_ServiceDesc.Streams[1], MessageService_MessageServerStreamFactor_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MessageServiceStreamFactorReq, MessageServiceStreamFactorRes]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageService_MessageServerStreamFactorClient = grpc.ServerStreamingClient[MessageServiceStreamFactorRes]

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility.
type MessageServiceServer interface {
	MessageUnary(context.Context, *MessageUnaryReq) (*MessageUnaryRes, error)
	MessageServerStream(*MessaageServerStreamReq, grpc.ServerStreamingServer[MessageServerStreamRes]) error
	MessageServerStreamFactor(*MessageServiceStreamFactorReq, grpc.ServerStreamingServer[MessageServiceStreamFactorRes]) error
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageServiceServer struct{}

func (UnimplementedMessageServiceServer) MessageUnary(context.Context, *MessageUnaryReq) (*MessageUnaryRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageUnary not implemented")
}
func (UnimplementedMessageServiceServer) MessageServerStream(*MessaageServerStreamReq, grpc.ServerStreamingServer[MessageServerStreamRes]) error {
	return status.Errorf(codes.Unimplemented, "method MessageServerStream not implemented")
}
func (UnimplementedMessageServiceServer) MessageServerStreamFactor(*MessageServiceStreamFactorReq, grpc.ServerStreamingServer[MessageServiceStreamFactorRes]) error {
	return status.Errorf(codes.Unimplemented, "method MessageServerStreamFactor not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}
func (UnimplementedMessageServiceServer) testEmbeddedByValue()                        {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	// If the following call pancis, it indicates UnimplementedMessageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_MessageUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageUnaryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).MessageUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_MessageUnary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).MessageUnary(ctx, req.(*MessageUnaryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_MessageServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MessaageServerStreamReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageServiceServer).MessageServerStream(m, &grpc.GenericServerStream[MessaageServerStreamReq, MessageServerStreamRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageService_MessageServerStreamServer = grpc.ServerStreamingServer[MessageServerStreamRes]

func _MessageService_MessageServerStreamFactor_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MessageServiceStreamFactorReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageServiceServer).MessageServerStreamFactor(m, &grpc.GenericServerStream[MessageServiceStreamFactorReq, MessageServiceStreamFactorRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageService_MessageServerStreamFactorServer = grpc.ServerStreamingServer[MessageServiceStreamFactorRes]

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MessageUnary",
			Handler:    _MessageService_MessageUnary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MessageServerStream",
			Handler:       _MessageService_MessageServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MessageServerStreamFactor",
			Handler:       _MessageService_MessageServerStreamFactor_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "message/message.proto",
}
