// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: message/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_message_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type MessageUnaryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageUnaryReq) Reset() {
	*x = MessageUnaryReq{}
	mi := &file_message_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUnaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUnaryReq) ProtoMessage() {}

func (x *MessageUnaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUnaryReq.ProtoReflect.Descriptor instead.
func (*MessageUnaryReq) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageUnaryReq) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type MessageUnaryRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageUnaryRes) Reset() {
	*x = MessageUnaryRes{}
	mi := &file_message_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUnaryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUnaryRes) ProtoMessage() {}

func (x *MessageUnaryRes) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUnaryRes.ProtoReflect.Descriptor instead.
func (*MessageUnaryRes) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{2}
}

func (x *MessageUnaryRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type MessaageServerStreamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessaageServerStreamReq) Reset() {
	*x = MessaageServerStreamReq{}
	mi := &file_message_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessaageServerStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessaageServerStreamReq) ProtoMessage() {}

func (x *MessaageServerStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessaageServerStreamReq.ProtoReflect.Descriptor instead.
func (*MessaageServerStreamReq) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{3}
}

func (x *MessaageServerStreamReq) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type MessageServerStreamRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageServerStreamRes) Reset() {
	*x = MessageServerStreamRes{}
	mi := &file_message_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageServerStreamRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageServerStreamRes) ProtoMessage() {}

func (x *MessageServerStreamRes) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageServerStreamRes.ProtoReflect.Descriptor instead.
func (*MessageServerStreamRes) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{4}
}

func (x *MessageServerStreamRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type MessageServiceStreamFactorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Initial       int32                  `protobuf:"varint,1,opt,name=initial,proto3" json:"initial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageServiceStreamFactorReq) Reset() {
	*x = MessageServiceStreamFactorReq{}
	mi := &file_message_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageServiceStreamFactorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageServiceStreamFactorReq) ProtoMessage() {}

func (x *MessageServiceStreamFactorReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageServiceStreamFactorReq.ProtoReflect.Descriptor instead.
func (*MessageServiceStreamFactorReq) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{5}
}

func (x *MessageServiceStreamFactorReq) GetInitial() int32 {
	if x != nil {
		return x.Initial
	}
	return 0
}

type MessageServiceStreamFactorRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Factor        int32                  `protobuf:"varint,1,opt,name=factor,proto3" json:"factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageServiceStreamFactorRes) Reset() {
	*x = MessageServiceStreamFactorRes{}
	mi := &file_message_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageServiceStreamFactorRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageServiceStreamFactorRes) ProtoMessage() {}

func (x *MessageServiceStreamFactorRes) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageServiceStreamFactorRes.ProtoReflect.Descriptor instead.
func (*MessageServiceStreamFactorRes) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{6}
}

func (x *MessageServiceStreamFactorRes) GetFactor() int32 {
	if x != nil {
		return x.Factor
	}
	return 0
}

var File_message_message_proto protoreflect.FileDescriptor

const file_message_message_proto_rawDesc = "" +
	"\n" +
	"\x15message/message.proto\x12\amessage\"B\n" +
	"\x04User\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\"4\n" +
	"\x0fMessageUnaryReq\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.message.UserR\x04user\")\n" +
	"\x0fMessageUnaryRes\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"<\n" +
	"\x17MessaageServerStreamReq\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.message.UserR\x04user\"0\n" +
	"\x16MessageServerStreamRes\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"9\n" +
	"\x1dMessageServiceStreamFactorReq\x12\x18\n" +
	"\ainitial\x18\x01 \x01(\x05R\ainitial\"7\n" +
	"\x1dMessageServiceStreamFactorRes\x12\x16\n" +
	"\x06factor\x18\x01 \x01(\x05R\x06factor2\xa5\x02\n" +
	"\x0eMessageService\x12D\n" +
	"\fMessageUnary\x12\x18.message.MessageUnaryReq\x1a\x18.message.MessageUnaryRes\"\x00\x12\\\n" +
	"\x13MessageServerStream\x12 .message.MessaageServerStreamReq\x1a\x1f.message.MessageServerStreamRes\"\x000\x01\x12o\n" +
	"\x19MessageServerStreamFactor\x12&.message.MessageServiceStreamFactorReq\x1a&.message.MessageServiceStreamFactorRes\"\x000\x01B\x10Z\x0eprotos/messageb\x06proto3"

var (
	file_message_message_proto_rawDescOnce sync.Once
	file_message_message_proto_rawDescData []byte
)

func file_message_message_proto_rawDescGZIP() []byte {
	file_message_message_proto_rawDescOnce.Do(func() {
		file_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_message_proto_rawDesc), len(file_message_message_proto_rawDesc)))
	})
	return file_message_message_proto_rawDescData
}

var file_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_message_message_proto_goTypes = []any{
	(*User)(nil),                          // 0: message.User
	(*MessageUnaryReq)(nil),               // 1: message.MessageUnaryReq
	(*MessageUnaryRes)(nil),               // 2: message.MessageUnaryRes
	(*MessaageServerStreamReq)(nil),       // 3: message.MessaageServerStreamReq
	(*MessageServerStreamRes)(nil),        // 4: message.MessageServerStreamRes
	(*MessageServiceStreamFactorReq)(nil), // 5: message.MessageServiceStreamFactorReq
	(*MessageServiceStreamFactorRes)(nil), // 6: message.MessageServiceStreamFactorRes
}
var file_message_message_proto_depIdxs = []int32{
	0, // 0: message.MessageUnaryReq.user:type_name -> message.User
	0, // 1: message.MessaageServerStreamReq.user:type_name -> message.User
	1, // 2: message.MessageService.MessageUnary:input_type -> message.MessageUnaryReq
	3, // 3: message.MessageService.MessageServerStream:input_type -> message.MessaageServerStreamReq
	5, // 4: message.MessageService.MessageServerStreamFactor:input_type -> message.MessageServiceStreamFactorReq
	2, // 5: message.MessageService.MessageUnary:output_type -> message.MessageUnaryRes
	4, // 6: message.MessageService.MessageServerStream:output_type -> message.MessageServerStreamRes
	6, // 7: message.MessageService.MessageServerStreamFactor:output_type -> message.MessageServiceStreamFactorRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_message_proto_init() }
func file_message_message_proto_init() {
	if File_message_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_message_proto_rawDesc), len(file_message_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_message_proto_goTypes,
		DependencyIndexes: file_message_message_proto_depIdxs,
		MessageInfos:      file_message_message_proto_msgTypes,
	}.Build()
	File_message_message_proto = out.File
	file_message_message_proto_goTypes = nil
	file_message_message_proto_depIdxs = nil
}
