// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type News struct {
	ID          int64
	Source      int64
	Author      sql.NullString
	Title       sql.NullString
	Description sql.NullString
	Publishedat sql.NullTime
}

type Source struct {
	ID         string
	SourceID   string
	SourceName string
}
