// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: news.sql

package database

import (
	"context"
	"database/sql"
)

const createNews = `-- name: CreateNews :one
INSERT INTO news (
    source,
    author,
    title,
    description,
    publishedAt
) VALUES (
    $1, $2, $3, $4, NOW()
) RETURNING id, source, author, title, description, publishedat
`

type CreateNewsParams struct {
	Source      string
	Author      sql.NullString
	Title       sql.NullString
	Description sql.NullString
}

func (q *Queries) CreateNews(ctx context.Context, arg CreateNewsParams) (News, error) {
	row := q.db.QueryRowContext(ctx, createNews,
		arg.Source,
		arg.Author,
		arg.Title,
		arg.Description,
	)
	var i News
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Author,
		&i.Title,
		&i.Description,
		&i.Publishedat,
	)
	return i, err
}

const getSingleNews = `-- name: GetSingleNews :one
SELECT n.id, n.source, n.author, n.title, n.description, n.publishedat, S.source_name FROM news N
INNER JOIN source S ON S.id = N.source
WHERE N.id = $1 LIMIT 1
`

type GetSingleNewsRow struct {
	ID          int64
	Source      string
	Author      sql.NullString
	Title       sql.NullString
	Description sql.NullString
	Publishedat sql.NullTime
	SourceName  string
}

func (q *Queries) GetSingleNews(ctx context.Context, id int64) (GetSingleNewsRow, error) {
	row := q.db.QueryRowContext(ctx, getSingleNews, id)
	var i GetSingleNewsRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Author,
		&i.Title,
		&i.Description,
		&i.Publishedat,
		&i.SourceName,
	)
	return i, err
}

const getSourceNews = `-- name: GetSourceNews :many
SELECT n.id, n.source, n.author, n.title, n.description, n.publishedat, S.source_name FROM news N
INNER JOIN source S ON S.id = N.source
WHERE N.source = $1
`

type GetSourceNewsRow struct {
	ID          int64
	Source      string
	Author      sql.NullString
	Title       sql.NullString
	Description sql.NullString
	Publishedat sql.NullTime
	SourceName  string
}

func (q *Queries) GetSourceNews(ctx context.Context, source string) ([]GetSourceNewsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSourceNews, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSourceNewsRow
	for rows.Next() {
		var i GetSourceNewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Author,
			&i.Title,
			&i.Description,
			&i.Publishedat,
			&i.SourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
