// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/greet.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetingName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetingName) Reset() {
	*x = GreetingName{}
	mi := &file_api_greet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetingName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetingName) ProtoMessage() {}

func (x *GreetingName) ProtoReflect() protoreflect.Message {
	mi := &file_api_greet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetingName.ProtoReflect.Descriptor instead.
func (*GreetingName) Descriptor() ([]byte, []int) {
	return file_api_greet_proto_rawDescGZIP(), []int{0}
}

func (x *GreetingName) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GreetingName) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GreetingName  *GreetingName          `protobuf:"bytes,1,opt,name=greeting_name,json=greetingName,proto3" json:"greeting_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_api_greet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_greet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_api_greet_proto_rawDescGZIP(), []int{1}
}

func (x *MessageRequest) GetGreetingName() *GreetingName {
	if x != nil {
		return x.GreetingName
	}
	return nil
}

type MessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageReply) Reset() {
	*x = MessageReply{}
	mi := &file_api_greet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReply) ProtoMessage() {}

func (x *MessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_greet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReply.ProtoReflect.Descriptor instead.
func (*MessageReply) Descriptor() ([]byte, []int) {
	return file_api_greet_proto_rawDescGZIP(), []int{2}
}

func (x *MessageReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type GreetMessageManyServerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GreetName     *GreetingName          `protobuf:"bytes,1,opt,name=greet_name,json=greetName,proto3" json:"greet_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetMessageManyServerReq) Reset() {
	*x = GreetMessageManyServerReq{}
	mi := &file_api_greet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetMessageManyServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetMessageManyServerReq) ProtoMessage() {}

func (x *GreetMessageManyServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_greet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetMessageManyServerReq.ProtoReflect.Descriptor instead.
func (*GreetMessageManyServerReq) Descriptor() ([]byte, []int) {
	return file_api_greet_proto_rawDescGZIP(), []int{3}
}

func (x *GreetMessageManyServerReq) GetGreetName() *GreetingName {
	if x != nil {
		return x.GreetName
	}
	return nil
}

type GreetMessageManyServerRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetMessageManyServerRes) Reset() {
	*x = GreetMessageManyServerRes{}
	mi := &file_api_greet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetMessageManyServerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetMessageManyServerRes) ProtoMessage() {}

func (x *GreetMessageManyServerRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_greet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetMessageManyServerRes.ProtoReflect.Descriptor instead.
func (*GreetMessageManyServerRes) Descriptor() ([]byte, []int) {
	return file_api_greet_proto_rawDescGZIP(), []int{4}
}

func (x *GreetMessageManyServerRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type LongGreetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      *GreetingName          `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LongGreetRequest) Reset() {
	*x = LongGreetRequest{}
	mi := &file_api_greet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LongGreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongGreetRequest) ProtoMessage() {}

func (x *LongGreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_greet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongGreetRequest.ProtoReflect.Descriptor instead.
func (*LongGreetRequest) Descriptor() ([]byte, []int) {
	return file_api_greet_proto_rawDescGZIP(), []int{5}
}

func (x *LongGreetRequest) GetGreeting() *GreetingName {
	if x != nil {
		return x.Greeting
	}
	return nil
}

type LongGreetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LongGreetResponse) Reset() {
	*x = LongGreetResponse{}
	mi := &file_api_greet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LongGreetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongGreetResponse) ProtoMessage() {}

func (x *LongGreetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_greet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongGreetResponse.ProtoReflect.Descriptor instead.
func (*LongGreetResponse) Descriptor() ([]byte, []int) {
	return file_api_greet_proto_rawDescGZIP(), []int{6}
}

func (x *LongGreetResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type GreetEveryoneReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      *GreetingName          `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetEveryoneReq) Reset() {
	*x = GreetEveryoneReq{}
	mi := &file_api_greet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetEveryoneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetEveryoneReq) ProtoMessage() {}

func (x *GreetEveryoneReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_greet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetEveryoneReq.ProtoReflect.Descriptor instead.
func (*GreetEveryoneReq) Descriptor() ([]byte, []int) {
	return file_api_greet_proto_rawDescGZIP(), []int{7}
}

func (x *GreetEveryoneReq) GetGreeting() *GreetingName {
	if x != nil {
		return x.Greeting
	}
	return nil
}

type GreetEveryoneRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetEveryoneRes) Reset() {
	*x = GreetEveryoneRes{}
	mi := &file_api_greet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetEveryoneRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetEveryoneRes) ProtoMessage() {}

func (x *GreetEveryoneRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_greet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetEveryoneRes.ProtoReflect.Descriptor instead.
func (*GreetEveryoneRes) Descriptor() ([]byte, []int) {
	return file_api_greet_proto_rawDescGZIP(), []int{8}
}

func (x *GreetEveryoneRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_api_greet_proto protoreflect.FileDescriptor

const file_api_greet_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/greet.proto\x12\x03api\"J\n" +
	"\fGreetingName\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\"H\n" +
	"\x0eMessageRequest\x126\n" +
	"\rgreeting_name\x18\x01 \x01(\v2\x11.api.GreetingNameR\fgreetingName\"&\n" +
	"\fMessageReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"M\n" +
	"\x19GreetMessageManyServerReq\x120\n" +
	"\n" +
	"greet_name\x18\x01 \x01(\v2\x11.api.GreetingNameR\tgreetName\"3\n" +
	"\x19GreetMessageManyServerRes\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"A\n" +
	"\x10LongGreetRequest\x12-\n" +
	"\bgreeting\x18\x01 \x01(\v2\x11.api.GreetingNameR\bgreeting\"+\n" +
	"\x11LongGreetResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"A\n" +
	"\x10GreetEveryoneReq\x12-\n" +
	"\bgreeting\x18\x01 \x01(\v2\x11.api.GreetingNameR\bgreeting\"*\n" +
	"\x10GreetEveryoneRes\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\xf6\x02\n" +
	"\fGreetService\x128\n" +
	"\fGreetMessage\x12\x13.api.MessageRequest\x1a\x11.api.MessageReply\"\x00\x12\\\n" +
	"\x16GreetMessageManyServer\x12\x1e.api.GreetMessageManyServerReq\x1a\x1e.api.GreetMessageManyServerRes\"\x000\x01\x12J\n" +
	"\x15LongGreetClientStream\x12\x15.api.LongGreetRequest\x1a\x16.api.LongGreetResponse\"\x00(\x01\x12C\n" +
	"\rGreetEveryone\x12\x15.api.GreetEveryoneReq\x1a\x15.api.GreetEveryoneRes\"\x00(\x010\x01\x12=\n" +
	"\x11GreetWithDeadline\x12\x13.api.MessageRequest\x1a\x11.api.MessageReply\"\x00B\fZ\n" +
	"protos/apib\x06proto3"

var (
	file_api_greet_proto_rawDescOnce sync.Once
	file_api_greet_proto_rawDescData []byte
)

func file_api_greet_proto_rawDescGZIP() []byte {
	file_api_greet_proto_rawDescOnce.Do(func() {
		file_api_greet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_greet_proto_rawDesc), len(file_api_greet_proto_rawDesc)))
	})
	return file_api_greet_proto_rawDescData
}

var file_api_greet_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_greet_proto_goTypes = []any{
	(*GreetingName)(nil),              // 0: api.GreetingName
	(*MessageRequest)(nil),            // 1: api.MessageRequest
	(*MessageReply)(nil),              // 2: api.MessageReply
	(*GreetMessageManyServerReq)(nil), // 3: api.GreetMessageManyServerReq
	(*GreetMessageManyServerRes)(nil), // 4: api.GreetMessageManyServerRes
	(*LongGreetRequest)(nil),          // 5: api.LongGreetRequest
	(*LongGreetResponse)(nil),         // 6: api.LongGreetResponse
	(*GreetEveryoneReq)(nil),          // 7: api.GreetEveryoneReq
	(*GreetEveryoneRes)(nil),          // 8: api.GreetEveryoneRes
}
var file_api_greet_proto_depIdxs = []int32{
	0, // 0: api.MessageRequest.greeting_name:type_name -> api.GreetingName
	0, // 1: api.GreetMessageManyServerReq.greet_name:type_name -> api.GreetingName
	0, // 2: api.LongGreetRequest.greeting:type_name -> api.GreetingName
	0, // 3: api.GreetEveryoneReq.greeting:type_name -> api.GreetingName
	1, // 4: api.GreetService.GreetMessage:input_type -> api.MessageRequest
	3, // 5: api.GreetService.GreetMessageManyServer:input_type -> api.GreetMessageManyServerReq
	5, // 6: api.GreetService.LongGreetClientStream:input_type -> api.LongGreetRequest
	7, // 7: api.GreetService.GreetEveryone:input_type -> api.GreetEveryoneReq
	1, // 8: api.GreetService.GreetWithDeadline:input_type -> api.MessageRequest
	2, // 9: api.GreetService.GreetMessage:output_type -> api.MessageReply
	4, // 10: api.GreetService.GreetMessageManyServer:output_type -> api.GreetMessageManyServerRes
	6, // 11: api.GreetService.LongGreetClientStream:output_type -> api.LongGreetResponse
	8, // 12: api.GreetService.GreetEveryone:output_type -> api.GreetEveryoneRes
	2, // 13: api.GreetService.GreetWithDeadline:output_type -> api.MessageReply
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_greet_proto_init() }
func file_api_greet_proto_init() {
	if File_api_greet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_greet_proto_rawDesc), len(file_api_greet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_greet_proto_goTypes,
		DependencyIndexes: file_api_greet_proto_depIdxs,
		MessageInfos:      file_api_greet_proto_msgTypes,
	}.Build()
	File_api_greet_proto = out.File
	file_api_greet_proto_goTypes = nil
	file_api_greet_proto_depIdxs = nil
}
