// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: calculator.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateSumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstNum      int32                  `protobuf:"varint,1,opt,name=FirstNum,proto3" json:"FirstNum,omitempty"`
	SecondNum     int32                  `protobuf:"varint,2,opt,name=SecondNum,proto3" json:"SecondNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateSumRequest) Reset() {
	*x = CalculateSumRequest{}
	mi := &file_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateSumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateSumRequest) ProtoMessage() {}

func (x *CalculateSumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateSumRequest.ProtoReflect.Descriptor instead.
func (*CalculateSumRequest) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateSumRequest) GetFirstNum() int32 {
	if x != nil {
		return x.FirstNum
	}
	return 0
}

func (x *CalculateSumRequest) GetSecondNum() int32 {
	if x != nil {
		return x.SecondNum
	}
	return 0
}

type CalculateSumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateSumResponse) Reset() {
	*x = CalculateSumResponse{}
	mi := &file_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateSumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateSumResponse) ProtoMessage() {}

func (x *CalculateSumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateSumResponse.ProtoReflect.Descriptor instead.
func (*CalculateSumResponse) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateSumResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_calculator_proto protoreflect.FileDescriptor

const file_calculator_proto_rawDesc = "" +
	"\n" +
	"\x10calculator.proto\x12\x06protos\"O\n" +
	"\x13CalculateSumRequest\x12\x1a\n" +
	"\bFirstNum\x18\x01 \x01(\x05R\bFirstNum\x12\x1c\n" +
	"\tSecondNum\x18\x02 \x01(\x05R\tSecondNum\".\n" +
	"\x14CalculateSumResponse\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\x05R\x06Result2W\n" +
	"\x11CalculatorService\x12B\n" +
	"\x03Sum\x12\x1b.protos.CalculateSumRequest\x1a\x1c.protos.CalculateSumResponse\"\x00B\fZ\n" +
	"protos/apib\x06proto3"

var (
	file_calculator_proto_rawDescOnce sync.Once
	file_calculator_proto_rawDescData []byte
)

func file_calculator_proto_rawDescGZIP() []byte {
	file_calculator_proto_rawDescOnce.Do(func() {
		file_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)))
	})
	return file_calculator_proto_rawDescData
}

var file_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_calculator_proto_goTypes = []any{
	(*CalculateSumRequest)(nil),  // 0: protos.CalculateSumRequest
	(*CalculateSumResponse)(nil), // 1: protos.CalculateSumResponse
}
var file_calculator_proto_depIdxs = []int32{
	0, // 0: protos.CalculatorService.Sum:input_type -> protos.CalculateSumRequest
	1, // 1: protos.CalculatorService.Sum:output_type -> protos.CalculateSumResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_proto_init() }
func file_calculator_proto_init() {
	if File_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_proto_depIdxs,
		MessageInfos:      file_calculator_proto_msgTypes,
	}.Build()
	File_calculator_proto = out.File
	file_calculator_proto_goTypes = nil
	file_calculator_proto_depIdxs = nil
}
