// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: calculate/calculate.proto

package calculate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CalculateService_CalculateSum_FullMethodName             = "/calculate.CalculateService/CalculateSum"
	CalculateService_PrimeNumberDecomposition_FullMethodName = "/calculate.CalculateService/PrimeNumberDecomposition"
	CalculateService_ComputeAverage_FullMethodName           = "/calculate.CalculateService/ComputeAverage"
	CalculateService_FindMaximum_FullMethodName              = "/calculate.CalculateService/FindMaximum"
)

// CalculateServiceClient is the client API for CalculateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculateServiceClient interface {
	// unary call
	CalculateSum(ctx context.Context, in *CalculateSumRequest, opts ...grpc.CallOption) (*CalculateSumResponse, error)
	// server streaming
	PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberDecompositionReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PrimeNumberDecompositionRes], error)
	// client streaming
	ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ComputeAverageReq, ComputeAverageRes], error)
	// duplex rpc
	FindMaximum(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FindMaximumReq, FindMaximumRes], error)
}

type calculateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculateServiceClient(cc grpc.ClientConnInterface) CalculateServiceClient {
	return &calculateServiceClient{cc}
}

func (c *calculateServiceClient) CalculateSum(ctx context.Context, in *CalculateSumRequest, opts ...grpc.CallOption) (*CalculateSumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateSumResponse)
	err := c.cc.Invoke(ctx, CalculateService_CalculateSum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculateServiceClient) PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberDecompositionReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PrimeNumberDecompositionRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CalculateService_ServiceDesc.Streams[0], CalculateService_PrimeNumberDecomposition_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PrimeNumberDecompositionReq, PrimeNumberDecompositionRes]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalculateService_PrimeNumberDecompositionClient = grpc.ServerStreamingClient[PrimeNumberDecompositionRes]

func (c *calculateServiceClient) ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ComputeAverageReq, ComputeAverageRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CalculateService_ServiceDesc.Streams[1], CalculateService_ComputeAverage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ComputeAverageReq, ComputeAverageRes]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalculateService_ComputeAverageClient = grpc.ClientStreamingClient[ComputeAverageReq, ComputeAverageRes]

func (c *calculateServiceClient) FindMaximum(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FindMaximumReq, FindMaximumRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CalculateService_ServiceDesc.Streams[2], CalculateService_FindMaximum_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FindMaximumReq, FindMaximumRes]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalculateService_FindMaximumClient = grpc.BidiStreamingClient[FindMaximumReq, FindMaximumRes]

// CalculateServiceServer is the server API for CalculateService service.
// All implementations must embed UnimplementedCalculateServiceServer
// for forward compatibility.
type CalculateServiceServer interface {
	// unary call
	CalculateSum(context.Context, *CalculateSumRequest) (*CalculateSumResponse, error)
	// server streaming
	PrimeNumberDecomposition(*PrimeNumberDecompositionReq, grpc.ServerStreamingServer[PrimeNumberDecompositionRes]) error
	// client streaming
	ComputeAverage(grpc.ClientStreamingServer[ComputeAverageReq, ComputeAverageRes]) error
	// duplex rpc
	FindMaximum(grpc.BidiStreamingServer[FindMaximumReq, FindMaximumRes]) error
	mustEmbedUnimplementedCalculateServiceServer()
}

// UnimplementedCalculateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCalculateServiceServer struct{}

func (UnimplementedCalculateServiceServer) CalculateSum(context.Context, *CalculateSumRequest) (*CalculateSumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateSum not implemented")
}
func (UnimplementedCalculateServiceServer) PrimeNumberDecomposition(*PrimeNumberDecompositionReq, grpc.ServerStreamingServer[PrimeNumberDecompositionRes]) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumberDecomposition not implemented")
}
func (UnimplementedCalculateServiceServer) ComputeAverage(grpc.ClientStreamingServer[ComputeAverageReq, ComputeAverageRes]) error {
	return status.Errorf(codes.Unimplemented, "method ComputeAverage not implemented")
}
func (UnimplementedCalculateServiceServer) FindMaximum(grpc.BidiStreamingServer[FindMaximumReq, FindMaximumRes]) error {
	return status.Errorf(codes.Unimplemented, "method FindMaximum not implemented")
}
func (UnimplementedCalculateServiceServer) mustEmbedUnimplementedCalculateServiceServer() {}
func (UnimplementedCalculateServiceServer) testEmbeddedByValue()                          {}

// UnsafeCalculateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculateServiceServer will
// result in compilation errors.
type UnsafeCalculateServiceServer interface {
	mustEmbedUnimplementedCalculateServiceServer()
}

func RegisterCalculateServiceServer(s grpc.ServiceRegistrar, srv CalculateServiceServer) {
	// If the following call pancis, it indicates UnimplementedCalculateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CalculateService_ServiceDesc, srv)
}

func _CalculateService_CalculateSum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateSumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculateServiceServer).CalculateSum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalculateService_CalculateSum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculateServiceServer).CalculateSum(ctx, req.(*CalculateSumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculateService_PrimeNumberDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberDecompositionReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculateServiceServer).PrimeNumberDecomposition(m, &grpc.GenericServerStream[PrimeNumberDecompositionReq, PrimeNumberDecompositionRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalculateService_PrimeNumberDecompositionServer = grpc.ServerStreamingServer[PrimeNumberDecompositionRes]

func _CalculateService_ComputeAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculateServiceServer).ComputeAverage(&grpc.GenericServerStream[ComputeAverageReq, ComputeAverageRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalculateService_ComputeAverageServer = grpc.ClientStreamingServer[ComputeAverageReq, ComputeAverageRes]

func _CalculateService_FindMaximum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculateServiceServer).FindMaximum(&grpc.GenericServerStream[FindMaximumReq, FindMaximumRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalculateService_FindMaximumServer = grpc.BidiStreamingServer[FindMaximumReq, FindMaximumRes]

// CalculateService_ServiceDesc is the grpc.ServiceDesc for CalculateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalculateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculate.CalculateService",
	HandlerType: (*CalculateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateSum",
			Handler:    _CalculateService_CalculateSum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecomposition",
			Handler:       _CalculateService_PrimeNumberDecomposition_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ComputeAverage",
			Handler:       _CalculateService_ComputeAverage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FindMaximum",
			Handler:       _CalculateService_FindMaximum_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calculate/calculate.proto",
}
